development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10

:queues:
  - default
  - active_storage_analysis
  - active_storage_purge

:schedule:
  scrap_rates_job:
    cron: "0 0/1 * * *" # "At minute 0 past every hour from 0 through 23."
    class: ScrapRatesJob
